export const foot={
    title:[
        {
            icon:'icon-banshou1-copy',
            name:'预约维修服务',
        },
           {
            icon:'icon-tian',
            name:'7天无理由退货',
        },
           {
            icon:'icon-tian1',
            name:'15天免费换货',
        },
           {
            icon:'icon-gift',
            name:'满99元包邮',
        },
           {
            icon:'icon-Frame1',
            name:'520余家售后网点',
        },
    ],
    bottom:[
        {
            name:'帮助中心',
            txt:[
                '账户管理','购物指南','订单操作'
            ]
        },
        {
            name:'服务支持',
            txt:[
                '售后政策','自助服务','相关下载',
            ]
        },
        {
            name:'线下门店',
            txt:[
                '小米之家','服务网点','授权体验店'
            ]
        },
        {
            name:'关于小米',
            txt:[
            '了解小米','加入小米','投资者关系','企业社会责任','廉洁举报'
            ]
        },
        {
            name:'关于我们',
            txt:[
                '新浪微博','官方微信','联系我们','公益基金会'
            ]
        },
        {
            name:'特色服务',
            txt:[
                'F码通道','礼物码','防伪查询'
            ]
        },
    ]
}