export const falsh=[
    {
        active:true,
        date:'10:00',
        time:{
            active:true,
            hou:0,
            min:0,
            sec:0,
            num:3600,
        },
        state:{
            one:'抢购中',
            two:'距结束',
            three:'即将开始',
        },
        commodity:[
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/b464671ac030e3da494b279bac705b63.jpg',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:41,
                percent:0,
            },
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/b464671ac030e3da494b279bac705b63.jpg',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:900,
                percent:0,
            },
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/b464671ac030e3da494b279bac705b63.jpg',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:41,
                percent:0,
            },
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/b464671ac030e3da494b279bac705b63.jpg',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:41,
                percent:0,
            }
        ]

    },
    {
        active:false,
        date:'14:00',
        time:{
            active:false,
            hou:0,
            min:0,
            sec:0,
            num:3600,
        },
        state:{
            one:'抢购中',
            two:'距结束',
            three:'即将开始',
        },
        commodity:[
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/d3480d56fd89dc2f80e2ec1653e718d1.jpg',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:156,
                percent:0,
            }
        ]

    },
    {
        active:false,
        date:'20:00',
        time:{
            active:false,
            hou:0,
            min:0,
            sec:0,
            num:3600,
        },
        state:{
            one:'抢购中',
            two:'距结束',
            three:'即将开始',
        },
        commodity:[
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/5a7cfd3bca771a62a7a7fba221ef8e47.jpg',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:200,
                percent:0,
            }
        ]

    },
    {
        active:false,
        date:'22:00',
        time:{
            active:false,
            hou:0,
            min:0,
            sec:0,
            num:3600,
        },
        state:{
            one:'抢购中',
            two:'距结束',
            three:'即将开始',
        },
        commodity:[
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/a714c996352f94cbde6747cd6392c041.jpg',
                name:'智能积木 公路赛车 白色 掰掰掰大师的萨芬撒',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:41,
                percent:0,
            }
        ]

    },
    {
        active:false,
        date:'00:00',
        time:{
            active:false,
            hou:0,
            min:0,
            sec:0,
            num:3600,
        },
        state:{
            one:'抢购中',
            two:'距结束',
            three:'即将开始',
        },
        commodity:[
            {
                img:'//cdn.cnbj1.fds.api.mi-img.com/mi-mall/a9acf081397fa6e610f75d70e69e9ca2.png',
                name:'智能积木 公路赛车 白色',
                txt:'烧脑搭建，尽兴狂奔',
                nowmoney:'209.00',
                oldmoney:'299',
                buy:'登陆后抢购',
                num:1000,
                buy_num:600,
                percent:0,
            }
        ]

    },
]